version: 0.2
phases:
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Python code...
      - pip install -r requirements.txt
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - 'Dockerfile'
    - Dockerrun.aws.json
    - requirements.txt
    - application.py